Add TDP 50
mstable/MIPs pull request #129
Opened 2022-09-02 06:23 UTC by mzero2nine

Happy Friday herr @dimsome, 

Could you please review this and merge when possible? Not immediate, as will publish on Monday barring no strong objections or changes :)

2022-09-02 07:46 UTC, dimsome requested changes
Added few comments

2022-09-02 07:46 UTC, dimsome commented on TDP/tdp-50.md
> +author: Cam Soulsby (@camsoulsby),
trailing comma, please remove

2022-09-02 07:46 UTC, dimsome commented on TDP/tdp-50.md
> +- supporting mStableDAO restructuring (as outlined in TDP 47) by enabling mStableDAO and its subDAOs to continue operating as a entity-less DAO while still retaining the flexibility to hire and compe
link to TDP 47

2022-09-02 07:46 UTC, dimsome commented on TDP/tdp-50.md
> +As part of the restructuring process outlined in [TDP 47: mStable Restructure - Compensation Model & subDAO Funding Request Framework](https://forum.mstable.org/t/tdp-47-mstable-restructure-compensat
link besser zum TDP in repo?

2022-09-02 07:46 UTC, dimsome commented on TDP/tdp-50.md
> +mStableDAO is an entity-less DAO with no wrapping legal entity and many mStable contributors are currently being compensated directly from the DAO in cryptocurrency. As part of the restructuring proc
link zur repo

2022-09-02 07:46 UTC, dimsome commented on TDP/tdp-50.md
> +For the mStableDAO, the Implementation Facilitators will be the mStable TreasuryDAO Operational Signers. They will help to facilitate creation of contributor agreements only as approved through Meta
vielleicht addressen hier?

2022-09-03 07:44 UTC, mzero2nine commented on TDP/tdp-50.md
> +For the mStableDAO, the Implementation Facilitators will be the mStable TreasuryDAO Operational Signers. They will help to facilitate creation of contributor agreements only as approved through Meta
Ich glaube, dass wollten die WorkDAO Leute so. Ich kann aber gerne die Addressen noch dazufuegen.

2022-09-03 07:45 UTC, mzero2nine commented on TDP/tdp-50.md
> +author: Cam Soulsby (@camsoulsby),
fixed

2022-09-03 07:45 UTC, mzero2nine commented on TDP/tdp-50.md
> +- supporting mStableDAO restructuring (as outlined in TDP 47) by enabling mStableDAO and its subDAOs to continue operating as a entity-less DAO while still retaining the flexibility to hire and compe
fixed

2022-09-03 07:45 UTC, mzero2nine commented on TDP/tdp-50.md
> +As part of the restructuring process outlined in [TDP 47: mStable Restructure - Compensation Model & subDAO Funding Request Framework](https://forum.mstable.org/t/tdp-47-mstable-restructure-compensat
yessir, fixed

2022-09-03 07:45 UTC, mzero2nine commented on TDP/tdp-50.md
> +mStableDAO is an entity-less DAO with no wrapping legal entity and many mStable contributors are currently being compensated directly from the DAO in cryptocurrency. As part of the restructuring proc
yas

2022-09-04 10:01 UTC, dimsome approved these changes

2022-09-04 10:01 UTC, merged