Create tdp-51.md
mstable/MIPs pull request #131
Opened 2022-10-10 15:26 UTC by jeshli

Add TreasuryDAO Charter TDP

2022-10-10 15:35 UTC, dimsome requested changes
Please use the consistent structure.

E.g.: https://raw.githubusercontent.com/mstable/MIPs/master/TDP/tdp-36.md

2022-10-10 15:35 UTC, dimsome commented on TDP/tdp-51.md
> +# TreasuryDAO Charter
Please use the header template, see other TDPs.

e.g.:

```
---
tdp: 49
title: Funding Request - mStable Ecosystem subDAO (Sep-Dec 2022)
status: Proposed
author: Fungus (@fungalarmy),  Cam Soulsby (@camsoulsby),  mZeroNine (@mzero2nine)
discussions-to: https://forum.mstable.org/t/funding-request-mstable-ecosystem-subdao-sep-dec-2022/927
created: 2022-08-26
---
```

2022-10-10 15:35 UTC, dimsome commented on TDP/tdp-51.md
> +## Quick Summary
We usually use `Simple Summary`

2022-10-10 15:35 UTC, dimsome commented on TDP/tdp-51.md
> +## Abstract
I would make the abstract shorter, it's really just an abstract.

2022-10-10 15:35 UTC, dimsome commented on TDP/tdp-51.md
> +It is the mission of the TreasuryDAO to secure runway to ensure that the mStableDAO Operations are sufficiently funded while investing a portion of its assets into key opportunities in the ecosystem
Please add a `motivation` part. Just outlining quickly why this is important. You can just reshift some of the passages around.

2022-10-10 15:35 UTC, dimsome commented on TDP/tdp-51.md
> +As one of its primary goals, the TreasuryDAO wants to conservatively and sustainably grow mStable treasury assets in its custody.
This part belongs in `## Specification`

2022-10-10 15:35 UTC, dimsome commented on TDP/tdp-51.md
> +## Treasury Strategy
This should be a h3? `###`

2022-10-10 15:35 UTC, dimsome commented on TDP/tdp-51.md
> +##### Secure immediate runway (minimum 12 months) (Capital Preservation):
Not sure there are #####? Just use bold text if you have to go deeper than h3

2022-10-15 05:04 UTC, jeshli commented
Now consistent  ;P

2022-10-17 06:01 UTC, merged