Add MIP 14, Bump Status
mstable/MIPs pull request #32
Opened 2021-07-06 12:42 UTC by dimsome

2021-07-06 15:59 UTC, alsco77 approved these changes

2021-07-06 16:00 UTC, alsco77 requested changes

2021-07-06 16:00 UTC, alsco77 commented on MIPS/mip-14.md
> +MIP: 14
Change capitalisation

2021-07-06 16:04 UTC, dimsome commented on MIPS/mip-14.md
> +MIP: 14
done, thanks!

2021-07-07 10:20 UTC, alsco77 approved these changes

2021-07-07 10:20 UTC, merged