Add TDP 37 & Update a bunch of Headers
mstable/MIPs pull request #92
Opened 2022-03-23 11:00 UTC by mzero2nine

Hi @dimsome 

I added TDP 37 and updated a bunch of outdated headers. Would be great if you could quickly review and merge, thanks!

2022-03-23 11:07 UTC, dimsome requested changes
just one smool change :)

2022-03-23 11:07 UTC, dimsome commented on MCCP/mccp-19.md
>  status: WIP
proposed?

2022-03-23 11:25 UTC, mzero2nine commented on MCCP/mccp-19.md
>  status: WIP
Good catch, there's always one smol one isn't there? :D

2022-03-28 09:07 UTC, dimsome commented on MCCP/mccp-19.md
>  status: WIP
cool thanks

2022-03-28 09:07 UTC, dimsome approved these changes

2022-03-28 09:07 UTC, dimsome approved these changes
lgtm

2022-03-28 09:07 UTC, merged